# This is an action to generate our dependency graph and commit it to the repo
# Credit to https://medium.com/google-developer-experts/how-to-display-your-android-project-dependency-graph-in-your-readme-file-e52dcadafa7a

name: Generate Dependency Graph

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-dependency-graph:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # The gradle script needs Graphviz to generate the graphics
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Generate Dependency Graph
        run: ./gradlew projectDependencyGraph

      - name: Commmit
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update dependency graph'
      
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

